Repository agilgur5/react-signature-canvas, pull requests merged in 2025-03, with the labels that each got.

#126 fix(pkg): add `types` to `package.json#exports`
  package.json
Labels: kind: bug, scope: types

#130 refactor: use `types` consistently instead of `typings`
  package.json
  tsconfig.build.json
  types/trim-canvas.d.ts
Labels: scope: types

#131 fix(pkg): move `types` above `default`
  package.json
Labels: kind: bug, scope: types

#132 deps: fix install on Node 22.14+ by updating `canvas` et al
  package-lock.json
  package.json
Labels: kind: bug, scope: upstream, kind: optimization, kind: internal, scope: dependencies
